name: plot-IBGE-spatial-dataset

on: [push]

jobs:
    deploy-cloud-runner:
        runs-on: [ubuntu-latest]
        container: docker://dvcorg/cml-py3:latest

        steps:
          - uses: actions/checkout@v2
            

          - name: cml_run
            shell: bash

            env:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
                                       

            run: |
                  
                  
                  echo "## Model run" > report.md
                  
                  pip install -r requirements.txt
                  
                  
                  python train.py >> report.md # | tee logfile.log
                   
                  echo "## Model metrics" >> report.md
                  
                  cat metrics.txt >> report.md
                  
                  
                  echo "## Data Viz" >> report.md
                  
                  cml-publish feature_importance.png --md --title 'Feature Importance' >> report.md
                  
                  cml-publish residuals.png --md --title 'residuals'>> report.md
                  
                  
              
            
